/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApisIndexRouteImport } from './routes/apis.index'
import { Route as ApisProviderApiRouteImport } from './routes/apis.$provider.$api'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApisRoute,
} as any)
const ApisProviderApiRoute = ApisProviderApiRouteImport.update({
  id: '/$provider/$api',
  path: '/$provider/$api',
  getParentRoute: () => ApisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apis': typeof ApisRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/apis/': typeof ApisIndexRoute
  '/apis/$provider/$api': typeof ApisProviderApiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/apis': typeof ApisIndexRoute
  '/apis/$provider/$api': typeof ApisProviderApiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apis': typeof ApisRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/apis/': typeof ApisIndexRoute
  '/apis/$provider/$api': typeof ApisProviderApiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apis'
    | '/developers'
    | '/guides'
    | '/login'
    | '/providers'
    | '/signup'
    | '/apis/'
    | '/apis/$provider/$api'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developers'
    | '/guides'
    | '/login'
    | '/providers'
    | '/signup'
    | '/apis'
    | '/apis/$provider/$api'
  id:
    | '__root__'
    | '/'
    | '/apis'
    | '/developers'
    | '/guides'
    | '/login'
    | '/providers'
    | '/signup'
    | '/apis/'
    | '/apis/$provider/$api'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApisRoute: typeof ApisRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  ProvidersRoute: typeof ProvidersRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/': {
      id: '/apis/'
      path: '/'
      fullPath: '/apis/'
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof ApisRoute
    }
    '/apis/$provider/$api': {
      id: '/apis/$provider/$api'
      path: '/$provider/$api'
      fullPath: '/apis/$provider/$api'
      preLoaderRoute: typeof ApisProviderApiRouteImport
      parentRoute: typeof ApisRoute
    }
  }
}

interface ApisRouteChildren {
  ApisIndexRoute: typeof ApisIndexRoute
  ApisProviderApiRoute: typeof ApisProviderApiRoute
}

const ApisRouteChildren: ApisRouteChildren = {
  ApisIndexRoute: ApisIndexRoute,
  ApisProviderApiRoute: ApisProviderApiRoute,
}

const ApisRouteWithChildren = ApisRoute._addFileChildren(ApisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApisRoute: ApisRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  ProvidersRoute: ProvidersRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
